## Mybatis 配置
#mybatis:
#  configuration:
#    # 驼峰自动转下划线
#    map-underscore-to-camel-case: true
#    default-enum-type-handler: com.example.demo.infrastructure.config.mybatis.typehandler.VoTypeHandler
#  # Mapper 别名配置, 这是 Spring boot 提供的兼容配置
#  #-> , 挖jar包: org.mybatis.spring.boot.autoconfigure.MybatisProperties
#  #-> , 或者官方文档: <a href="https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/">
#  #->     mybatis-spring-boot-autoconfigure – Introduction</a>
#  type-aliases-package: com.example.demo.domain.entity
#  type-handlers-package: com.example.demo.infrastructure.config.mybatis

# Spring 配置
spring:
  ## Spring Data JPA
  ##-> <a href="https://blog.csdn.net/WZH577/article/details/99698187">Hibernate数据库配置项中命名策略说明</a>
  jpa:
    #    hibernate:
    #      # 【踩坑】Spring-Boot-2.2.x-Release: Spring Boot允许 Hibernate 选择要使用的方言，而不是根据检测到的数据库应用默认方言。
    #      #-> 也就是说,，以前配置了方言，现在版本中要删除这些自定义项 (方言由 Hibernate 进行适配)。
    #      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #      ddl-auto: none
    #    show-sql: true
    #    open-in-view: true
    #    # Hibernate (Hibernate 5) 能够自行适配数据库方言以后, Spring boot 配置只能指定数据库及其平台
    #    database: mysql
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ### @Description 设计: 数据库结构不应该被框架操作
      ddl-auto: none
      ### @Tips 策略配置参照相应接口实现类的 API Docs (<class>SpringImplicitNamingStrategy</class>的实现有点坑)
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      format_sql: true
    show-sql: true
    open-in-view: true
  mvc:
    ### 配置静态资源访问前缀
    ###-> @Reference <class>org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties</class>
    static-path-pattern: /static/**
  ## 加载 dev 环境配置
  profiles:
    active: dev
  ## 配置静态资源路径 (默认配置失效)
  resources:
    static-locations[0]: classpath:/static/