# develop environment
# 服务配置
server:
  ## 端口
  port: 8081

# 项目个性化配置
webchat:
  ## 数据源配置
  ##-> TIPS: 个性化配置不应该与 Spring 等开发框架共用同一个命名空间, 故迁移.
  datasource:
    ### 主数据源
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # Spring Boot 2.xx 将默认的JDBC连接池从Tomcat更改为更快更好的HikariCP, 导致<item>url</item>需要改为<item>jdbc-url</item>
      jdbc-url: jdbc:mysql://localhost:3306/webchat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: User
      password: 123456
    ### 测试用的数据源
    test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: User
      password: 123456

# Spring 生态 - 配置
spring:
  # 开发环境关闭 Thymeleaf 的缓存
  thymeleaf:
    cache: false
#===== Use Redis in Spring =====#
# redis:
#    # Redis 数据库索引（默认为 0）
#    database: 0
#    # Redis 服务器地址
#    host: localhost
#    # Redis 服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password:
#    # 连接池最大连接数（若使用负值则表示没有限制） 默认 8
#    lettuce:
#      pool:
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
#==========#

# log 配置
logging:
  ## 输出级别
  level:
    com.favorites: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
    github.com.suitelhy.webchat.domain.repository.*: DEBUG
  file:
    ### 输出地址
    path: /user/local/log

## Mybatis 配置 (测试环境)
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
